app:
  port: 3002

  postgres:
    host: localhost
    port: 5432
    username: admin
    password: admin123
    database: mydb
    sync: true
    logging: true

  cassandra:
    contactPoints:
      - localhost
    dataCenter: datacenter1
    keyspace: material_service
    username: ""
    password: ""

  kafka:
    clientId: material-worker
    brokers:
      - localhost:9092
    groupId: material-worker-group
    retries: 8
    initialRetryTime: 100

  redis:
    host: localhost
    port: 6379
    password: ""
    db: 0

  snowflake:
    machineId: 2

  minio:
    endPoint: localhost
    port: 9000
    useSSL: false
    accessKey: minioadmin
    secretKey: minioadmin
    bucketName: material-worker
    region: us-east-1

