app:
  port: 3000

  postgres:
    host: localhost
    port: 5432
    username: admin
    password: admin123
    database: mydb
    sync: true
    logging: true

  cassandra:
    contactPoints:
      - localhost
    dataCenter: datacenter1
    keyspace: user_service
    username: ""
    password: ""

  kafka:
    clientId: user-service
    brokers:
      - localhost:9092
    groupId: user-service-group
    retries: 8
    initialRetryTime: 100

  redis:
    host: localhost
    port: 6379
    password: ""
    db: 0

  snowflake:
    machineId: 1
